# This is a default configuration file for Kobo-UNCaGED.

# Prefer saving books to the external SD card if your device has one, and a
# card is inserted. Otherwise books are saved to the internal storage
preferSDCard = false

# Prefer sending kepub files to your Kobo, when they exist in your Calibre library.
# If this setting is false, epub files will be the preferred format.
preferKepub = true

# Provide a comma separated list of passwords. Kobo-UNCaGED will try each of these in turn,
# untill or if one succeeds. Eg:
# passwordList = ["password1","password2","passwordn"]
passwordList = []

# Provide more verbose logging
enableDebug = false

# The following options tweak aspects of the thumbnail generation process
[thumbnail]
    # Choose what level of thumbnails you want generated. Options are "all", "partial", "none"
    # "all" generates all thumbnails, including that used on the sleep screen.
    # "partial" generates thumbnails used in the library views and home screen, and is faster than "all"
    # "none" generates no thumbnails, and let's the Kobo software generate them.
    generateLevel = "all"

    # Choose which resize algorithm to use when generating thumbnails. Allowed options are
    # "bilinear", "bicubic", "lanczos2", "lanczos3". Default is "bicubic"
    resizeAlgorithm = "bicubic"

    # Choose a Jpeg quality level between 0 and 100. Default is 90
    jpegQuality = 90