name: Build Kobo UNCaGED

on: [push, pull_request]

jobs:
  build_ku:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: ./build.sh

      - name: Prepare directory for upload
        run: |
          mkdir -p build/Kobo-UNCaGED
          cd build/Kobo-UNCaGED
          unzip ../Kobo-UNCaGED.zip

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Kobo-UNCaGED
          path: build/Kobo-UNCaGED

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          generate_release_notes: true
          files: |
            build/Kobo-UNCaGED.zip
          token: ${{ secrets.GITHUB_TOKEN }}
